//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОказаниеУслуг.
    /// </summary>
    // *** Start programmer edit section *** (ОказаниеУслуг CustomAttributes)

    // *** End programmer edit section *** (ОказаниеУслуг CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОказаниеУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Stomat.Услуга fУслуга;
        
        private IIS.Stomat.Запись fЗапись;
        
        // *** Start programmer edit section *** (ОказаниеУслуг CustomMembers)

        // *** End programmer edit section *** (ОказаниеУслуг CustomMembers)

        
        /// <summary>
        /// ОказаниеУслуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Услуга CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Stomat.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Get start)
                IIS.Stomat.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Stomat.Запись.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Запись CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Запись CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запись"})]
        public virtual IIS.Stomat.Запись Запись
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Get start)
                IIS.Stomat.Запись result = this.fЗапись;
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОказаниеУслуг.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОказаниеУслуг CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОказаниеУслуг CustomAttributes)
    public class DetailArrayOfОказаниеУслуг : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Stomat.DetailArrayOfОказаниеУслуг members)

        // *** End programmer edit section *** (IIS.Stomat.DetailArrayOfОказаниеУслуг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОказаниеУслуг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОказаниеУслуг.
        /// </summary>
        public DetailArrayOfОказаниеУслуг(IIS.Stomat.Запись fЗапись) : 
                base(typeof(ОказаниеУслуг), ((ICSSoft.STORMNET.DataObject)(fЗапись)))
        {
        }
        
        public IIS.Stomat.ОказаниеУслуг this[int index]
        {
            get
            {
                return ((IIS.Stomat.ОказаниеУслуг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Stomat.ОказаниеУслуг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
